services:
  - type: web
    name: tooly-bot
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    numInstances: 1
    envVars:
      - key: DISCORD_TOKEN
        sync: false
    autoDeploy: true